# Generated by Django 3.0.5 on 2020-04-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('case_type', models.CharField(choices=[('confirmed', 'confirmed'), ('deaths', 'deaths'), ('recovered', 'recovered')], default='confirmed', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_country', models.CharField(default='', max_length=100)),
                ('case_types', models.ManyToManyField(to='corona_plots.CaseType')),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(default='', max_length=100)),
                ('case_types', models.ManyToManyField(to='corona_plots.CaseType')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.CharField(default='', max_length=100)),
                ('case_types', models.ManyToManyField(to='corona_plots.CaseType')),
                ('region_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='corona_plots.CountryRegion')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('friendly_name', models.CharField(max_length=100)),
                ('friendly_hash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('case_types', models.ManyToManyField(to='corona_plots.CaseType')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corona_plots.County')),
                ('province_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='corona_plots.ProvinceState')),
                ('region_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='corona_plots.CountryRegion')),
            ],
        ),
        migrations.CreateModel(
            name='EntryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('case_status_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corona_plots.CaseType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='corona_plots.Location')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='province_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='corona_plots.ProvinceState'),
        ),
        migrations.AddField(
            model_name='county',
            name='region_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='corona_plots.CountryRegion'),
        ),
        migrations.CreateModel(
            name='CountPercentIncreaseEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corona_plots.Entry')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='corona_plots.EntryDate')),
            ],
            bases=('corona_plots.entry',),
        ),
        migrations.CreateModel(
            name='CountIncreaseEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corona_plots.Entry')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='corona_plots.EntryDate')),
            ],
            bases=('corona_plots.entry',),
        ),
        migrations.CreateModel(
            name='CountEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corona_plots.Entry')),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='corona_plots.EntryDate')),
            ],
            bases=('corona_plots.entry',),
        ),
    ]
